version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps'
    groups:
      actions:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps'
    groups:
      bundler:
        applies-to: version-updates
        update-types:
          - minor
          - patch
