---
parallel: true
ruby_version: 2.0

ignore:
  - '*.gemspec'
  - research/**/*
  - pkg/**/*
  - Gemfile:
      - Style/HashSyntax
  - Rakefile:
      - Layout/HeredocIndentation

plugins:
  - rubocop-thread_safety
