# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "hoe-highline", "~>0.1.0", :group => [:development, :test]
gem "hoe-mercurial", "~>1.4.0", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "rspec", "~>2.0", :group => [:development, :test]
gem "rake", "~>10.0", :group => [:development, :test]
gem "hoe", "~>3.4", :group => [:development, :test]

# vim: syntax=ruby
