# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Autotest; end
module ::Text::Format; end
module SimpleCov::Formatter::RcovFormatter; end
module SimpleCov::Formatter::SublimeRubyCoverageFormatter; end
module SimpleCov::Formatter::VimFormatter; end
